// frontend/components/dashboard/CompactAssigneeRating.vue
<template>
  <div
    v-if="summary"
    class="mt-0.5 flex flex-wrap items-center gap-1"
    :aria-label="`Note ${summary.averageRating.toFixed(1)} sur 5, ${formatReviewsCount(summary.reviewsCount)}`"
  >
    <div class="flex items-center gap-px" aria-hidden="true">
      <UIcon
        v-for="star in 5"
        :key="star"
        :name="star <= filledStars ? 'i-heroicons-star-solid' : 'i-heroicons-star'"
        class="h-2.5 w-2.5"
        :class="star <= filledStars ? 'text-amber-400' : 'text-gray-300 dark:text-gray-600'"
      />
    </div>
    <span class="text-xs font-semibold tabular-nums text-gray-900 dark:text-white">
      {{ summary.averageRating.toFixed(1) }}
    </span>
    <span class="text-xs text-gray-400 dark:text-gray-500">·</span>
    <span class="text-xs font-medium text-gray-500 dark:text-gray-400">
      {{ formatReviewsCount(summary.reviewsCount) }}
    </span>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import {
  formatReviewsCount,
  type AssigneeReviewSummary,
} from '~/utils/assignee-review-display';

const props = defineProps<{
  summary: AssigneeReviewSummary | null | undefined;
}>();

const filledStars = computed(() =>
  Math.min(5, Math.max(0, Math.round(props.summary?.averageRating ?? 0))),
);
</script>

// apps/mobile/src/features/appointments/detail/components/CompactAssigneeRating.tsx
import { colors } from '@/theme';
import { StyleSheet, Text, View } from 'react-native';
import { Star } from 'lucide-react-native';
import { spacing } from '@/theme';
import { fontFamily, fontSize } from '@/theme/typography';
import {
  formatReviewsCount,
  type AssigneeReviewSummary,
} from '../utils/assignee-review-display';

interface Props {
  summary: AssigneeReviewSummary | null | undefined;
}

/** Note + nombre d'avis sous le nom d'un intervenant. */
export function CompactAssigneeRating({ summary }: Props) {
  if (!summary) return null;

  const { averageRating, reviewsCount } = summary;
  const filledStars = Math.min(5, Math.max(0, Math.round(averageRating)));

  return (
    <View
      style={styles.row}
      accessibilityLabel={`Note ${averageRating.toFixed(1)} sur 5, ${formatReviewsCount(reviewsCount)}`}
    >
      <View style={styles.stars}>
        {Array.from({ length: 5 }, (_, index) => (
          <Star
            key={index}
            size={11}
            color={index < filledStars ? colors.star : colors.border}
            fill={index < filledStars ? colors.starFill : 'transparent'}
            strokeWidth={1.5}
          />
        ))}
      </View>
      <Text style={styles.rating}>{averageRating.toFixed(1)}</Text>
      <Text style={styles.separator}>·</Text>
      <Text style={styles.count}>{formatReviewsCount(reviewsCount)}</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[1],
    flexWrap: 'wrap',
  },
  stars: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 1,
  },
  rating: {
    fontFamily: fontFamily.semiBold,
    fontSize: fontSize.xs,
    color: colors.textPrimary,
    fontVariant: ['tabular-nums'],
  },
  separator: {
    fontFamily: fontFamily.regular,
    fontSize: fontSize.xs,
    color: colors.textTertiary,
  },
  count: {
    fontFamily: fontFamily.medium,
    fontSize: fontSize.xs,
    color: colors.textSecondary,
  },
});
