// frontend/components/prescription/NursePrescriptionScopeHelp.vue
<template>
  <div
    class="rounded-xl border border-primary/20 bg-primary/5 dark:bg-primary/10 p-4 sm:p-5 flex flex-col sm:flex-row sm:items-center gap-4"
    role="region"
    aria-label="Aide prescription infirmière"
  >
    <div class="flex gap-3 min-w-0 flex-1">
      <div
        class="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-primary/15 text-primary"
        aria-hidden="true"
      >
        <UIcon name="i-lucide-scale" class="w-5 h-5" />
      </div>
      <div class="min-w-0 space-y-1">
        <p class="text-sm font-semibold text-gray-900 dark:text-white leading-snug">
          Que puis-je prescrire en tant qu’infirmier ?
        </p>
        <p class="text-xs text-muted leading-relaxed">
          Liste réglementaire (L4311-1, arrêté 2026), limites et usage dans Cary.
        </p>
      </div>
    </div>
    <UButton
      size="sm"
      color="primary"
      variant="soft"
      class="shrink-0 self-start sm:self-center"
      icon="i-lucide-book-open"
      @click="open = true"
    >
      Voir la liste
    </UButton>
  </div>

  <UModal
    v-model:open="open"
    :ui="{
      content: 'max-w-2xl w-[calc(100vw-1.5rem)] sm:w-full',
      body: 'p-0 sm:p-0',
    }"
  >
    <template #header>
      <div class="space-y-1 pr-8">
        <p class="text-lg font-semibold text-gray-900 dark:text-white">
          {{ scope.modalTitle }}
        </p>
        <p class="text-sm text-muted font-normal">
          {{ scope.modalSubtitle }}
        </p>
      </div>
    </template>

    <template #body>
      <div class="max-h-[min(72vh,640px)] overflow-y-auto overscroll-contain px-4 sm:px-6 pb-6 space-y-6">
        <p class="text-sm text-gray-700 dark:text-gray-300 leading-relaxed">
          {{ scope.intro }}
        </p>

        <div
          class="rounded-lg border border-sky-200/80 dark:border-sky-800/50 bg-sky-50/90 dark:bg-sky-950/30 px-4 py-3.5 flex gap-3"
        >
          <UIcon name="i-lucide-info" class="w-5 h-5 text-sky-600 dark:text-sky-400 shrink-0 mt-0.5" />
          <p class="text-xs sm:text-sm text-sky-950 dark:text-sky-100 leading-relaxed">
            {{ scope.caryNotice }}
          </p>
        </div>

        <section class="space-y-3">
          <h3 class="text-xs font-semibold uppercase tracking-wide text-muted">
            Domaines autorisés
          </h3>
          <UAccordion
            :items="accordionItems"
            type="multiple"
            :ui="accordionUi"
          >
            <template #default="{ item }">
              <span class="text-sm font-medium text-gray-900 dark:text-white">{{ item.label }}</span>
            </template>
            <template #content="{ item }">
              <p class="text-sm text-gray-600 dark:text-gray-400 whitespace-pre-line leading-relaxed">
                {{ item.content }}
              </p>
            </template>
          </UAccordion>
        </section>

        <section class="space-y-3">
          <h3 class="text-xs font-semibold uppercase tracking-wide text-muted">
            Règles essentielles
          </h3>
          <ul class="space-y-3">
            <li
              v-for="rule in scope.keyRules"
              :key="rule.id"
              class="rounded-lg border border-default/60 bg-muted/20 px-4 py-3"
            >
              <p class="text-sm font-medium text-gray-900 dark:text-white">{{ rule.title }}</p>
              <p class="text-xs text-muted mt-1 leading-relaxed">{{ rule.body }}</p>
            </li>
          </ul>
        </section>

        <section class="space-y-3">
          <h3 class="text-xs font-semibold uppercase tracking-wide text-muted">
            Textes officiels et références
          </h3>
          <ul class="space-y-2">
            <li
              v-for="src in scope.legalSources"
              :key="src.id"
              class="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-1 sm:gap-4 rounded-lg border border-default/50 px-4 py-3 hover:bg-muted/30 transition-colors"
            >
              <div class="min-w-0">
                <p class="text-sm font-medium text-gray-900 dark:text-white">{{ src.label }}</p>
                <p v-if="src.note" class="text-xs text-muted mt-0.5">{{ src.note }}</p>
                <p class="text-[11px] text-muted mt-1">
                  {{ src.publisher }}
                  <span v-if="src.publishedAt"> · {{ src.publishedAt }}</span>
                </p>
              </div>
              <UButton
                :to="src.url"
                target="_blank"
                rel="noopener noreferrer"
                size="xs"
                color="neutral"
                variant="ghost"
                icon="i-lucide-external-link"
                class="shrink-0 self-start"
              >
                Ouvrir
              </UButton>
            </li>
          </ul>
        </section>

        <p class="text-[11px] text-muted leading-relaxed border-t border-default/50 pt-4">
          {{ scope.disclaimer }}
          <span class="block mt-2 text-muted/80">
            Contenu Cary · révision {{ scope.version }} · maj. {{ formattedUpdatedAt }}
          </span>
        </p>
      </div>
    </template>

    <template #footer>
      <div class="flex justify-end w-full">
        <UButton color="neutral" variant="soft" @click="open = false">
          Fermer
        </UButton>
      </div>
    </template>
  </UModal>
</template>

<script setup lang="ts">
import {
  NURSE_PRESCRIPTION_SCOPE,
  nursePrescriptionScopeAccordionItems,
} from '@oneandlab/shared-utils';

const open = ref(false);
const scope = NURSE_PRESCRIPTION_SCOPE;
const accordionItems = nursePrescriptionScopeAccordionItems(scope);

const formattedUpdatedAt = computed(() => {
  try {
    return new Date(scope.updatedAt).toLocaleDateString('fr-FR', {
      day: 'numeric',
      month: 'long',
      year: 'numeric',
    });
  } catch {
    return scope.updatedAt;
  }
});

const accordionUi = {
  root: 'space-y-2',
  item: {
    base: 'border border-default/60 rounded-xl overflow-hidden bg-default/40',
    padding: 'p-0',
  },
  trigger: {
    base: 'flex items-center justify-between w-full text-left px-4 py-3.5 hover:bg-muted/40 transition-colors',
    padding: 'p-0',
  },
  content: {
    base: 'px-4 pb-4 pt-0 border-t border-default/40',
    padding: 'pt-3',
  },
};
</script>

// apps/mobile/src/features/prescriptions/components/NursePrescriptionScopeHelp.tsx
import { useAppColors } from '@/theme/use-app-colors';
import { useMemo, useState } from 'react';
import { Row } from '@/components/layout/primitives';
import { Linking, Pressable, StyleSheet, View } from 'react-native';
import { BookOpen, ChevronDown, ChevronUp, ExternalLink, Info, Scale } from 'lucide-react-native';
import {
  NURSE_PRESCRIPTION_SCOPE,
  type NursePrescriptionLegalSource,
  type NursePrescriptionScopeCategory,
} from '@oneandlab/shared-utils';
import { SheetModal } from '@/components/ui/SheetModal';
import { Button } from '@/components/ui/Button';
import { spacing, radius, iconSize, AppText, useStyles, font, type Theme } from '@/theme';

function formatUpdatedAt(iso: string): string {
  try {
    return new Date(iso).toLocaleDateString('fr-FR', {
      day: 'numeric',
      month: 'long',
      year: 'numeric',
    });
  } catch {
    return iso;
  }
}

function CategoryBlock({ category }: { category: NursePrescriptionScopeCategory }) {
  const c = useAppColors();
  const styles = useStyles(buildCategoryStyles);
  const [open, setOpen] = useState(false);

  return (
    <View style={styles.wrap}>
      <Pressable
        accessibilityRole="button"
        accessibilityState={{ expanded: open }}
        onPress={() => setOpen((v) => !v)}
      >
        <Row align="start" style={styles.trigger}>
        <View style={styles.triggerText}>
          <AppText style={styles.catTitle}>{category.title}</AppText>
          <AppText style={styles.catSummary} numberOfLines={open ? undefined : 2}>
            {category.summary}
          </AppText>
        </View>
        {open ? (
          <ChevronUp size={iconSize.sm} color={c.textSecondary} strokeWidth={2} />
        ) : (
          <ChevronDown size={iconSize.sm} color={c.textSecondary} strokeWidth={2} />
        )}
        </Row>
      </Pressable>
      {open ? (
        <View style={styles.body}>
          {category.items.map((item) => (
            <Row key={item.id} align="start" style={styles.bulletRow}>
              <AppText style={styles.bullet}>•</AppText>
              <AppText style={styles.itemText}>
                {item.label}
                {item.detail ? ` — ${item.detail}` : ''}
              </AppText>
            </Row>
          ))}
          {category.limits?.map((lim) => (
            <View key={lim} style={styles.limitBox}>
              <AppText style={styles.limitText}>{lim}</AppText>
            </View>
          ))}
        </View>
      ) : null}
    </View>
  );
}

function SourceRow({ source }: { source: NursePrescriptionLegalSource }) {
  const c = useAppColors();
  const styles = useStyles(buildSourceStyles);

  return (
    <Row align="start" style={styles.row}>
      <View style={styles.textCol}>
        <AppText style={styles.label}>{source.label}</AppText>
        {source.note ? <AppText style={styles.note}>{source.note}</AppText> : null}
        <AppText style={styles.meta}>
          {source.publisher}
          {source.publishedAt ? ` · ${source.publishedAt}` : ''}
        </AppText>
      </View>
      <Pressable
        accessibilityRole="link"
        accessibilityLabel={`Ouvrir ${source.label}`}
        hitSlop={8}
        onPress={() => Linking.openURL(source.url)}
        style={styles.linkBtn}
      >
        <ExternalLink size={iconSize.sm} color={c.primary} strokeWidth={2} />
      </Pressable>
    </Row>
  );
}

export function NursePrescriptionScopeHelp() {
  const c = useAppColors();
  const styles = useStyles(buildStyles);
  const [sheetOpen, setSheetOpen] = useState(false);
  const scope = NURSE_PRESCRIPTION_SCOPE;
  const updatedLabel = useMemo(() => formatUpdatedAt(scope.updatedAt), [scope.updatedAt]);

  return (
    <>
      <Row wrap align="start" style={styles.banner}>
        <View style={styles.bannerIcon}>
          <Scale size={iconSize.md} color={c.primary} strokeWidth={2} />
        </View>
        <View style={styles.bannerText}>
          <AppText style={styles.bannerTitle}>Que puis-je prescrire en tant qu’infirmier ?</AppText>
          <AppText style={styles.bannerSub}>
            Liste réglementaire (L4311-1, arrêté 2026), limites et usage Cary.
          </AppText>
        </View>
        <Button
          title="Voir la liste"
          size="sm"
          variant="outline"
          leftIcon={<BookOpen size={iconSize.xs} color={c.primary} strokeWidth={2} />}
          onPress={() => setSheetOpen(true)}
          style={styles.bannerBtn}
        />
      </Row>

      <SheetModal
        visible={sheetOpen}
        onClose={() => setSheetOpen(false)}
        title={scope.modalTitle}
        subtitle={scope.modalSubtitle}
        snapPoints={['92%']}
      >
        <AppText style={styles.intro}>{scope.intro}</AppText>

        <Row align="start" style={styles.caryNotice}>
          <Info size={iconSize.sm} color={c.primary} strokeWidth={2} style={styles.caryIcon} />
          <AppText style={styles.caryText}>{scope.caryNotice}</AppText>
        </Row>

        <AppText style={styles.sectionLabel}>Domaines autorisés</AppText>
        {scope.categories.map((cat) => (
          <CategoryBlock key={cat.id} category={cat} />
        ))}

        <AppText style={styles.sectionLabel}>Règles essentielles</AppText>
        {scope.keyRules.map((rule) => (
          <View key={rule.id} style={styles.ruleBox}>
            <AppText style={styles.ruleTitle}>{rule.title}</AppText>
            <AppText style={styles.ruleBody}>{rule.body}</AppText>
          </View>
        ))}

        <AppText style={styles.sectionLabel}>Textes officiels et références</AppText>
        {scope.legalSources.map((src) => (
          <SourceRow key={src.id} source={src} />
        ))}

        <AppText style={styles.disclaimer}>
          {scope.disclaimer}
          {'\n\n'}
          Contenu Cary · révision {scope.version} · maj. {updatedLabel}
        </AppText>
      </SheetModal>
    </>
  );
}

function buildStyles({ colors: c, fontSize }: Theme) {
  return {
    banner: {
      flexWrap: 'wrap',
      alignItems: 'flex-start',
      gap: spacing[3],
      padding: spacing[4],
      borderRadius: radius.xl,
      borderWidth: 1,
      borderColor: c.primaryMid,
      backgroundColor: c.primaryLight,
      marginBottom: spacing[3],
    },
    bannerIcon: {
      width: 40,
      height: 40,
      borderRadius: radius.lg,
      backgroundColor: c.primaryMid,
      alignItems: 'center',
      justifyContent: 'center',
    },
    bannerText: { flex: 1, minWidth: 160, gap: spacing[1] },
    bannerTitle: {
      ...font.semiBold,
      fontSize: fontSize.sm,
      color: c.textPrimary,
    },
    bannerSub: {
      ...font.regular,
      fontSize: fontSize.xs,
      color: c.textSecondary,
      lineHeight: 18,
    },
    bannerBtn: { alignSelf: 'flex-start' },
    intro: {
      ...font.regular,
      fontSize: fontSize.sm,
      color: c.textPrimary,
      lineHeight: 22,
      marginBottom: spacing[4],
    },
    caryNotice: {
      gap: spacing[3],
      padding: spacing[3],
      borderRadius: radius.lg,
      backgroundColor: c.primaryLight,
      borderWidth: 1,
      borderColor: c.primaryMid,
      marginBottom: spacing[5],
    },
    caryIcon: { marginTop: 2 },
    caryText: {
      flex: 1,
      minWidth: 0,
      ...font.regular,
      fontSize: fontSize.xs,
      color: c.textPrimary,
      lineHeight: 18,
    },
    sectionLabel: {
      ...font.semiBold,
      fontSize: fontSize['2xs'],
      color: c.textSecondary,
      textTransform: 'uppercase',
      letterSpacing: 0.6,
      marginBottom: spacing[2],
      marginTop: spacing[2],
    },
    ruleBox: {
      padding: spacing[3],
      borderRadius: radius.lg,
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.surfaceAlt,
      marginBottom: spacing[2],
    },
    ruleTitle: {
      ...font.medium,
      fontSize: fontSize.sm,
      color: c.textPrimary,
    },
    ruleBody: {
      ...font.regular,
      fontSize: fontSize.xs,
      color: c.textSecondary,
      marginTop: spacing[1],
      lineHeight: 18,
    },
    disclaimer: {
      ...font.regular,
      fontSize: fontSize['2xs'],
      color: c.textSecondary,
      lineHeight: 17,
      marginTop: spacing[4],
      paddingTop: spacing[4],
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: c.border,
      marginBottom: spacing[6],
    },
  } satisfies Parameters<typeof StyleSheet.create>[0];
}

function buildCategoryStyles({ colors: c, fontSize }: Theme) {
  return {
    wrap: {
      borderWidth: 1,
      borderColor: c.border,
      borderRadius: radius.lg,
      overflow: 'hidden',
      marginBottom: spacing[2],
      backgroundColor: c.surface,
    },
    trigger: {
      alignItems: 'flex-start',
      gap: spacing[2],
      padding: spacing[3],
    },
    triggerText: { flex: 1, minWidth: 0, gap: spacing[0.5] },
    catTitle: {
      ...font.medium,
      fontSize: fontSize.sm,
      color: c.textPrimary,
    },
    catSummary: {
      ...font.regular,
      fontSize: fontSize.xs,
      color: c.textSecondary,
      lineHeight: 17,
    },
    body: {
      paddingHorizontal: spacing[3],
      paddingBottom: spacing[3],
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: c.border,
      gap: spacing[1],
    },
    bulletRow: { gap: spacing[2], paddingRight: spacing[1] },
    bullet: { ...font.regular, fontSize: fontSize.sm, color: c.primary },
    itemText: {
      flex: 1,
      minWidth: 0,
      ...font.regular,
      fontSize: fontSize.xs,
      color: c.textPrimary,
      lineHeight: 18,
    },
    limitBox: {
      marginTop: spacing[2],
      padding: spacing[2],
      borderRadius: radius.md,
      backgroundColor: c.surfaceAlt,
    },
    limitText: {
      ...font.regular,
      fontSize: fontSize['2xs'],
      color: c.textSecondary,
      lineHeight: 16,
    },
  } satisfies Parameters<typeof StyleSheet.create>[0];
}

function buildSourceStyles({ colors: c, fontSize }: Theme) {
  return {
    row: {
      alignItems: 'flex-start',
      gap: spacing[2],
      padding: spacing[3],
      borderRadius: radius.lg,
      borderWidth: 1,
      borderColor: c.border,
      marginBottom: spacing[2],
    },
    textCol: { flex: 1, minWidth: 0, gap: spacing[0.5] },
    label: {
      ...font.medium,
      fontSize: fontSize.sm,
      color: c.textPrimary,
    },
    note: {
      ...font.regular,
      fontSize: fontSize.xs,
      color: c.textSecondary,
    },
    meta: {
      ...font.regular,
      fontSize: fontSize['2xs'],
      color: c.textSecondary,
    },
    linkBtn: {
      padding: spacing[2],
      borderRadius: radius.md,
    },
  } satisfies Parameters<typeof StyleSheet.create>[0];
}
