// frontend-build-tmp/components/prescription/PrescriptionProfileGapsAlert.vue
<template>
  <div
    v-if="gaps.length > 0"
    class="rounded-lg border border-amber-200 dark:border-amber-800/60 bg-amber-50 dark:bg-amber-900/20 p-4 flex gap-3"
    role="status"
  >
    <UIcon name="i-lucide-triangle-alert" class="w-5 h-5 text-amber-600 dark:text-amber-400 shrink-0 mt-0.5" />
    <div class="min-w-0 flex-1 space-y-3">
      <div>
        <p class="text-sm font-semibold text-gray-900 dark:text-gray-100">
          À compléter pour l'ordonnance
        </p>
        <p class="text-xs text-muted mt-1 leading-relaxed">
          Ces informations figureront sur le PDF. Vous pouvez générer quand même, mais le document sera incomplet.
        </p>
      </div>

      <div v-if="patientGaps.length > 0" class="space-y-1.5">
        <p class="text-[11px] font-semibold uppercase tracking-wide text-amber-700 dark:text-amber-300">
          Fiche patient
        </p>
        <div
          v-for="gap in patientGaps"
          :key="gap.id"
          class="flex flex-wrap items-center gap-x-2 gap-y-1 text-xs"
        >
          <span class="text-gray-800 dark:text-gray-200">· {{ gap.message }}</span>
          <button
            type="button"
            class="font-semibold text-primary hover:underline"
            @click="onGapAction(gap)"
          >
            {{ gap.actionLabel }}
          </button>
        </div>
      </div>

      <div v-if="prescriberGaps.length > 0" class="space-y-1.5">
        <p class="text-[11px] font-semibold uppercase tracking-wide text-amber-700 dark:text-amber-300">
          Votre profil
        </p>
        <div
          v-for="gap in prescriberGaps"
          :key="gap.id"
          class="flex flex-wrap items-center gap-x-2 gap-y-1 text-xs"
        >
          <span class="text-gray-800 dark:text-gray-200">· {{ gap.message }}</span>
          <button
            type="button"
            class="font-semibold text-primary hover:underline"
            @click="onGapAction(gap)"
          >
            {{ gap.actionLabel }}
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import type { PrescriptionProfileGap } from '@oneandlab/shared-utils';

const props = defineProps<{
  gaps: PrescriptionProfileGap[];
  patientId?: string;
  prescriberRole?: string;
}>();

const emit = defineEmits<{
  signPrescriber: [];
}>();

const patientGaps = computed(() => props.gaps.filter((g) => g.action === 'edit_patient'));
const prescriberGaps = computed(() => props.gaps.filter((g) => g.action !== 'edit_patient'));

function onGapAction(gap: PrescriptionProfileGap) {
  if (gap.action === 'edit_patient' && props.patientId) {
    navigateTo(`/profile?userId=${encodeURIComponent(props.patientId)}`);
    return;
  }
  if (gap.action === 'sign_prescriber') {
    emit('signPrescriber');
    return;
  }
  navigateTo('/profile');
}
</script>

// apps/mobile/src/features/prescriptions/components/PrescriptionProfileGapsAlert.tsx
import { layoutRowWrap } from '@/theme/layout-styles';
import { useAppColors } from '@/theme/use-app-colors';
import { Pressable, View } from 'react-native';
import { useRouter } from 'expo-router';
import { AlertTriangle } from 'lucide-react-native';
import { Cluster } from '@/components/layout/primitives';
import type { PrescriptionProfileGap } from '../utils/prescription-profile-gaps';
import { radius, spacing, iconSize, AppText, useStyles, font, type Theme } from '@/theme';

interface Props {
  gaps: PrescriptionProfileGap[];
  onEditPatient?: () => void;
  onSignPrescriber?: () => void;
  prescriberRole?: string;
}

export function PrescriptionProfileGapsAlert({
  gaps,
  onEditPatient,
  onSignPrescriber,
  prescriberRole,
}: Props) {
  const c = useAppColors();
  const styles = useStyles(buildStyles);
  const router = useRouter();

  if (gaps.length === 0) return null;

  const patientGaps = gaps.filter((g) => g.action === 'edit_patient');
  const prescriberGaps = gaps.filter((g) => g.action !== 'edit_patient');

  const onGapPress = (gap: PrescriptionProfileGap) => {
    if (gap.action === 'edit_patient') {
      onEditPatient?.();
      return;
    }
    if (gap.action === 'sign_prescriber') {
      onSignPrescriber?.();
      return;
    }
    if (prescriberRole === 'nurse') {
      router.push('/profile/nurse/coordinates');
      return;
    }
    router.push('/profile');
  };

  return (
    <Cluster
      align="start"
      gap={spacing[2.5]}
      style={styles.box}
      leading={<AlertTriangle size={iconSize.md} color={c.warning} strokeWidth={2.25} />}
    >
      <View style={styles.body}>
        <AppText style={styles.title}>À compléter pour l'ordonnance</AppText>
        <AppText style={styles.subtitle}>
          Ces informations figureront sur le PDF. Vous pouvez générer quand même, mais le document sera
          incomplet.
        </AppText>

        {patientGaps.length > 0 ? (
          <View style={styles.group}>
            <AppText style={styles.groupLabel}>Fiche patient</AppText>
            {patientGaps.map((gap) => (
              <GapRow key={gap.id} gap={gap} onPress={() => onGapPress(gap)} styles={styles} />
            ))}
          </View>
        ) : null}

        {prescriberGaps.length > 0 ? (
          <View style={styles.group}>
            <AppText style={styles.groupLabel}>Votre profil</AppText>
            {prescriberGaps.map((gap) => (
              <GapRow key={gap.id} gap={gap} onPress={() => onGapPress(gap)} styles={styles} />
            ))}
          </View>
        ) : null}
      </View>
    </Cluster>
  );
}

function GapRow({
  gap,
  onPress,
  styles,
}: {
  gap: PrescriptionProfileGap;
  onPress: () => void;
  styles: ReturnType<typeof buildStyles>;
}) {
  return (
    <View style={styles.row}>
      <AppText style={styles.rowMessage}>· {gap.message}</AppText>
      <Pressable onPress={onPress} hitSlop={6} accessibilityRole="button">
        <AppText style={styles.rowAction}>{gap.actionLabel}</AppText>
      </Pressable>
    </View>
  );
}

function buildStyles({ colors: c, fontSize }: Theme) {
  return {
    box: {
      padding: spacing[3],
      borderRadius: radius.lg,
      borderWidth: 1,
      borderColor: c.warningMid,
      backgroundColor: c.warningLight,
    },
    body: { minWidth: 0, flex: 1, gap: spacing[2] },
    title: {
      ...font.semiBold,
      fontSize: fontSize.sm,
      color: c.textPrimary,
    },
    subtitle: {
      ...font.regular,
      fontSize: fontSize.xs,
      color: c.textSecondary,
      lineHeight: fontSize.xs * 1.45,
    },
    group: { gap: spacing[1] },
    groupLabel: {
      ...font.semiBold,
      fontSize: fontSize.xs,
      color: c.warning,
      textTransform: 'uppercase' as const,
      letterSpacing: 0.3,
    },
    row: {
      ...layoutRowWrap(spacing[1.5]),
      alignItems: 'center' as const,
    },
    rowMessage: {
      minWidth: 0,
      ...font.medium,
      fontSize: fontSize.xs,
      color: c.textPrimary,
      flexShrink: 1,
    },
    rowAction: {
      ...font.semiBold,
      fontSize: fontSize.xs,
      color: c.primary,
    },
  };
}
