// frontend/components/nurse/PassageSimpleListRow.vue
<template>
  <div
    class="relative rounded-2xl border px-3.5 py-3 shadow-md ring-1 ring-black/[0.04] dark:ring-white/[0.06]"
    :class="cardClass"
  >
    <div class="flex items-center gap-2.5">
      <button type="button" class="min-w-0 flex-1 text-left" @click="$emit('open-detail')">
        <div class="flex min-w-0 flex-wrap items-center gap-1.5">
          <p
            class="truncate text-sm font-semibold leading-tight tracking-tight"
            :class="mutedText ? 'text-gray-500 dark:text-gray-400' : 'text-gray-900 dark:text-white'"
          >
            {{ stop.patient_name }}
          </p>
          <UBadge v-if="isNext && !done && !absent" color="primary" variant="subtle" size="xs">
            Suivant
          </UBadge>
          <UBadge v-if="absent && absenceLabel" color="neutral" variant="subtle" size="xs">
            {{ absenceLabel }}
          </UBadge>
        </div>
        <NurseTourStopCare
          :stop="stop"
          :categories="categories"
          embedded
          list-compact
          :class="mutedText ? 'opacity-70' : ''"
        />
        <div v-if="scheduleMeta" class="mt-1 flex min-w-0 items-center gap-1.5">
          <UIcon name="i-lucide-clock" class="h-3.5 w-3.5 shrink-0 text-gray-400 dark:text-gray-500" />
          <span class="text-xs font-medium text-gray-500 dark:text-gray-400">{{ scheduleMeta }}</span>
        </div>
        <div
          v-if="routeKmLabel || routeDriveMinLabel"
          class="mt-1 flex min-w-0 flex-wrap items-center gap-x-2.5 gap-y-0.5"
        >
          <span v-if="routeKmLabel" class="inline-flex items-center gap-1">
            <UIcon name="i-lucide-route" class="h-3.5 w-3.5 shrink-0 text-gray-400 dark:text-gray-500" />
            <span class="text-xs font-medium text-gray-500 dark:text-gray-400">{{ routeKmLabel }}</span>
          </span>
          <span v-if="routeDriveMinLabel" class="inline-flex items-center gap-1">
            <UIcon name="i-lucide-car" class="h-3.5 w-3.5 shrink-0 text-gray-400 dark:text-gray-500" />
            <span class="text-xs font-medium text-gray-500 dark:text-gray-400">{{ routeDriveMinLabel }}</span>
          </span>
        </div>
      </button>

      <button
        type="button"
        class="flex h-9 w-9 shrink-0 items-center justify-center rounded-full border transition-colors"
        :class="checkClass"
        :aria-label="absent ? 'Gérer l\'absence du patient' : done ? 'Passage effectué, appuyer pour annuler' : 'Marquer comme effectué'"
        @click="absent ? $emit('manage-absence') : $emit('toggle-done')"
      >
        <UIcon
          :name="absent ? 'i-lucide-user-x' : 'i-lucide-check'"
          class="h-[18px] w-[18px]"
          :class="absent ? 'text-gray-500 dark:text-gray-400' : done ? 'text-white' : 'text-gray-400 opacity-40 dark:text-gray-500'"
        />
      </button>

      <button
        type="button"
        class="flex h-8 w-8 shrink-0 items-center justify-center rounded-full text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-800"
        aria-label="Gérer l'absence"
        @click="$emit('manage-absence')"
      >
        <UIcon name="i-lucide-calendar-off" class="h-4 w-4" />
      </button>
    </div>

    <div v-if="showReorder" class="mt-2 flex justify-end gap-1">
      <UButton
        size="xs"
        color="neutral"
        variant="ghost"
        icon="i-lucide-chevron-up"
        :disabled="index === 0 || saving"
        aria-label="Monter"
        @click="$emit('move-up')"
      />
      <UButton
        size="xs"
        color="neutral"
        variant="ghost"
        icon="i-lucide-chevron-down"
        :disabled="index >= total - 1 || saving"
        aria-label="Descendre"
        @click="$emit('move-down')"
      />
    </div>
  </div>
</template>

<script setup lang="ts">
import type { NurseTourStop } from '~/composables/useNurseTourWeb';
import type { CareCategoryRowMinimal } from '~/utils/care-icons';
import { isTourStopAbsent } from '@oneandlab/shared-utils';
import {
  formatPassageTourStopTimeLabel,
  resolvePassageTourStopRouteLabels,
} from '~/utils/passage-tour-display';

const props = withDefaults(
  defineProps<{
    stop: NurseTourStop;
    index: number;
    total: number;
    isNext?: boolean;
    saving?: boolean;
    showReorder?: boolean;
    categories?: CareCategoryRowMinimal[];
  }>(),
  { categories: () => [], isNext: false },
);

defineEmits<{
  'toggle-done': [];
  'open-detail': [];
  'move-up': [];
  'move-down': [];
  'manage-absence': [];
}>();

const absent = computed(() => isTourStopAbsent(props.stop));
const done = computed(
  () =>
    !absent.value &&
    (props.stop.visit_status === 'done' || props.stop.status === 'completed'),
);
const mutedText = computed(() => done.value || absent.value);
const absenceLabel = computed(() => props.stop.patient_absence?.card_label_fr ?? '');

const cardClass = computed(() => {
  if (absent.value) {
    return 'border-gray-300 bg-gray-100 opacity-75 dark:border-gray-700 dark:bg-gray-800/60';
  }
  if (done.value) {
    return 'border-emerald-200 bg-emerald-50 dark:border-emerald-800/70 dark:bg-emerald-950/35';
  }
  if (props.isNext) {
    return 'border-primary-300 ring-1 ring-primary-200 dark:border-primary-700 dark:ring-primary-900/40 bg-white dark:bg-gray-900/50';
  }
  return 'border-gray-200 bg-white dark:border-gray-800 dark:bg-gray-900/50';
});

const checkClass = computed(() => {
  if (absent.value) {
    return 'border-gray-300 bg-gray-200 dark:border-gray-600 dark:bg-gray-700';
  }
  if (done.value) {
    return 'border-emerald-500 bg-emerald-500 shadow-sm';
  }
  return 'border-gray-300 bg-gray-50 dark:border-gray-600 dark:bg-gray-800';
});

const scheduleMeta = computed(() => {
  const parts: string[] = [formatPassageTourStopTimeLabel(props.stop)];
  if (props.stop.passage_duration_minutes) {
    parts.push(`${props.stop.passage_duration_minutes} min`);
  }
  return parts.filter(Boolean).join(' · ');
});

const routeLabels = computed(() => resolvePassageTourStopRouteLabels(props.stop, props.index));
const routeKmLabel = computed(() => routeLabels.value.kmLabel);
const routeDriveMinLabel = computed(() => routeLabels.value.driveMinLabel);
</script>

// apps/mobile/src/features/nurse-passage/components/PassageSimpleListRow.tsx
import { useAppColors } from '@/theme/use-app-colors';
import { Pressable, StyleSheet, View } from 'react-native';
import Animated, { FadeInDown } from 'react-native-reanimated';
import { Check, ChevronDown, ChevronUp, Car, Clock, Route, UserX } from 'lucide-react-native';
import { isTourStopAbsent } from '@oneandlab/shared-utils';
import { Cluster, Row } from '@/components/layout/primitives';
import { Badge } from '@/components/ui/Badge';
import { TourStopCareSection } from '@/features/tournee-nurse/components/TourStopCareSection';
import type { NurseTourStop } from '@/features/tournee-nurse/api/nurse-tour.service';
import { useAppointmentListCardStyles } from '@/utils/appointment-list-card-styles';
import {
  formatPassageDurationLabel,
  formatPassageTimeLabel,
  resolvePassageRouteListLabels,
} from '../utils/passage-display';
import { spacing, iconSize, AppText, useStyles, font, type Theme } from '@/theme';
import { hexToRgba } from '@/theme/color-utils';

type Props = {
  stop: NurseTourStop;
  index: number;
  total: number;
  isNext?: boolean;
  onPressName: () => void;
  onToggleDone: () => void;
  onMoveUp?: () => void;
  onMoveDown?: () => void;
  onManageAbsence?: () => void;
};

export function PassageSimpleListRow({
  stop,
  index,
  total,
  isNext = false,
  onPressName,
  onToggleDone,
  onMoveUp,
  onMoveDown,
  onManageAbsence,
}: Props) {
  const c = useAppColors();
  const styles = useStyles(buildStyles);
  const cardStyles = useAppointmentListCardStyles();
  const absent = isTourStopAbsent(stop);
  const done = !absent && (stop.visit_status === 'done' || stop.status === 'completed');
  const absenceLabel = stop.patient_absence?.card_label_fr;
  const timeLabel = formatPassageTimeLabel(stop);
  const durationLabel = formatPassageDurationLabel(stop);
  const { kmLabel, driveMinLabel } = resolvePassageRouteListLabels(stop, index);
  const scheduleMeta = [timeLabel, durationLabel].filter(Boolean).join(' · ');

  return (
    <Animated.View entering={FadeInDown.delay(index * 35).duration(280)} style={cardStyles.cardShell}>
      <View
        style={[
          cardStyles.card,
          styles.cardInner,
          absent && styles.cardAbsent,
          {
            backgroundColor: absent
              ? hexToRgba(c.textTertiary, 0.08)
              : done
                ? hexToRgba(c.success, 0.1)
                : c.surface,
            borderColor: absent
              ? hexToRgba(c.textTertiary, 0.22)
              : done
                ? hexToRgba(c.success, 0.28)
                : c.borderLight,
            opacity: absent ? 0.72 : 1,
          },
        ]}
      >
        <Cluster
          align="center"
          gap={spacing[2.5]}
          actions={
            <Pressable
              onPress={absent ? onManageAbsence : onToggleDone}
              disabled={absent && !onManageAbsence}
              hitSlop={{ top: 8, bottom: 8, left: 8, right: 8 }}
              style={styles.checkHit}
              accessibilityRole={absent ? 'button' : 'checkbox'}
              accessibilityState={absent ? undefined : { checked: done }}
              accessibilityLabel={
                absent
                  ? 'Gérer l\'absence du patient'
                  : done
                    ? 'Passage effectué, appuyer pour annuler'
                    : 'Marquer comme effectué'
              }
            >
              <View
                style={[
                  styles.checkOuter,
                  absent
                    ? {
                        borderColor: hexToRgba(c.textTertiary, 0.35),
                        backgroundColor: hexToRgba(c.textTertiary, 0.12),
                      }
                    : done
                      ? {
                          borderColor: c.success,
                          backgroundColor: c.success,
                        }
                      : {
                          borderColor: hexToRgba(c.textTertiary, 0.35),
                          backgroundColor: c.surfaceAlt,
                        },
                ]}
              >
                {absent ? (
                  <UserX size={iconSize.smMd} color={c.textTertiary} strokeWidth={2.3} />
                ) : (
                  <Check
                    size={iconSize.mdSm}
                    color={done ? '#FFFFFF' : c.textTertiary}
                    strokeWidth={2.5}
                    opacity={done ? 1 : 0.38}
                  />
                )}
              </View>
            </Pressable>
          }
        >
          <Pressable
            onPress={onPressName}
            onLongPress={onManageAbsence}
            style={styles.nameCol}
            accessibilityRole="button"
            accessibilityLabel={`Ouvrir le passage de ${stop.patient_name}`}
          >
            <Row gap={spacing[1.5]} align="center" wrap style={styles.nameRow}>
              <AppText
                style={[styles.name, styles.nameFlex, { color: done ? c.textSecondary : c.textPrimary }]}
                numberOfLines={1}
              >
                {stop.patient_name}
              </AppText>
              {isNext && !done && !absent ? (
                <Badge label="Suivant" variant="primary" size="sm" dot={false} />
              ) : null}
              {absent && absenceLabel ? (
                <Badge label={absenceLabel} variant="neutral" size="sm" dot={false} />
              ) : null}
            </Row>
            <TourStopCareSection stop={stop} embedded listCompact muted={done || absent} />
            {scheduleMeta ? (
              <Row gap={spacing[2]} align="center" style={styles.metaRow}>
                <View style={styles.metaIconWrap}>
                  <Clock size={iconSize['2xs']} color={c.textTertiary} strokeWidth={2.5} />
                </View>
                <AppText style={[styles.meta, { color: c.textTertiary }]}>{scheduleMeta}</AppText>
              </Row>
            ) : null}
            {kmLabel || driveMinLabel ? (
              <Row gap={spacing[2.5]} align="center" wrap style={styles.metaRow}>
                {kmLabel ? (
                  <Row gap={spacing[1]} align="center" style={styles.routeSegment}>
                    <Route size={iconSize['2xs']} color={c.textTertiary} strokeWidth={2.5} />
                    <AppText style={[styles.metaInline, { color: c.textTertiary }]}>{kmLabel}</AppText>
                  </Row>
                ) : null}
                {driveMinLabel ? (
                  <Row gap={spacing[1]} align="center" style={styles.routeSegment}>
                    <Car size={iconSize['2xs']} color={c.textTertiary} strokeWidth={2.5} />
                    <AppText style={[styles.metaInline, { color: c.textTertiary }]}>{driveMinLabel}</AppText>
                  </Row>
                ) : null}
              </Row>
            ) : null}
          </Pressable>
        </Cluster>

        {onMoveUp || onMoveDown ? (
          <Row justify="end" gap={spacing[2]} style={styles.reorderRow}>
            <Pressable
              onPress={onMoveUp}
              disabled={index === 0}
              style={[styles.reorderBtn, index === 0 && styles.reorderDisabled]}
              accessibilityLabel="Monter"
            >
              <ChevronUp size={iconSize.md} color={index === 0 ? c.textTertiary : c.textSecondary} />
            </Pressable>
            <Pressable
              onPress={onMoveDown}
              disabled={index >= total - 1}
              style={[styles.reorderBtn, index >= total - 1 && styles.reorderDisabled]}
              accessibilityLabel="Descendre"
            >
              <ChevronDown
                size={iconSize.md}
                color={index >= total - 1 ? c.textTertiary : c.textSecondary}
              />
            </Pressable>
          </Row>
        ) : null}
      </View>
    </Animated.View>
  );
}

function buildStyles({ fontSize }: Theme) {
  return {
    cardInner: {
      paddingVertical: spacing[3],
      paddingHorizontal: spacing[3.5],
    },
    cardAbsent: {},
    nameCol: { flex: 1, minWidth: 0, gap: spacing[0.5] },
    nameRow: { minWidth: 0, alignSelf: 'stretch' as const },
    nameFlex: { flexShrink: 1, minWidth: 0 },
    name: {
      ...font.semiBold,
      fontSize: fontSize.sm,
      letterSpacing: -0.15,
    },
    meta: {
      flex: 1,
      minWidth: 0,
      ...font.medium,
      fontSize: fontSize.xs,
    },
    metaInline: {
      ...font.medium,
      fontSize: fontSize.xs,
    },
    routeSegment: {
      flexShrink: 0,
    },
    metaRow: {
      marginTop: spacing[0.5],
      minWidth: 0,
      alignSelf: 'stretch' as const,
    },
    metaIconWrap: {
      width: 18,
      alignItems: 'center' as const,
      flexShrink: 0,
    },
    checkHit: {
      alignSelf: 'center' as const,
      alignItems: 'center' as const,
      justifyContent: 'center' as const,
    },
    checkOuter: {
      width: 36,
      height: 36,
      borderRadius: 18,
      borderWidth: StyleSheet.hairlineWidth * 2,
      alignItems: 'center' as const,
      justifyContent: 'center' as const,
    },
    reorderRow: { marginTop: spacing[2], paddingTop: spacing[1] },
    reorderBtn: { padding: spacing[1] },
    reorderDisabled: { opacity: 0.35 },
  };
}
