// frontend/components/nurse/TourViewTabs.vue
<template>
  <div class="mb-2 flex gap-2">
    <button
      v-for="tab in tabs"
      :key="tab.id"
      type="button"
      class="flex-1 rounded-xl border px-3 py-2.5 text-center text-sm font-semibold transition-colors"
      :class="
        active === tab.id
          ? 'border-primary-500 bg-primary-50 text-primary-700 dark:bg-primary-950/40 dark:text-primary-300'
          : 'border-gray-200 bg-white text-gray-600 hover:border-gray-300 dark:border-gray-800 dark:bg-gray-900 dark:text-gray-400'
      "
      role="tab"
      :aria-selected="active === tab.id"
      @click="$emit('update:active', tab.id)"
    >
      {{ tab.label }}
    </button>
  </div>
</template>

<script setup lang="ts">
import type { PassageTourViewTab } from '@oneandlab/shared-types';

defineProps<{
  active: PassageTourViewTab;
}>();

defineEmits<{
  'update:active': [tab: PassageTourViewTab];
}>();

const tabs: { id: PassageTourViewTab; label: string }[] = [
  { id: 'manual', label: 'Passage' },
  { id: 'intelligent', label: 'Passage intelligent' },
];
</script>

// apps/mobile/src/features/nurse-passage/components/TourViewTabs.tsx
import type { AppColors } from '@/theme/colors';
import { hexToRgba } from '@/theme/color-utils';
import { useThemedStyles } from '@/theme/use-themed-styles';
import { useAppColors } from '@/theme/use-app-colors';
import type { PassageTourViewTab } from '@oneandlab/shared-types';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { H_PADDING, radius, spacing } from '@/theme';
import { fontFamily, fontSize } from '@/theme/typography';

const TABS: { id: PassageTourViewTab; label: string }[] = [
  { id: 'manual', label: 'Passage' },
  { id: 'intelligent', label: 'Passage intelligent' },
];

type Props = {
  active: PassageTourViewTab;
  onChange: (tab: PassageTourViewTab) => void;
};

export function TourViewTabs({ active, onChange }: Props) {
  const c = useAppColors();
  const styles = useThemedStyles(buildStyles);

  return (
    <View style={styles.row}>
      {TABS.map((t) => {
        const selected = active === t.id;
        return (
          <Pressable
            key={t.id}
            onPress={() => onChange(t.id)}
            style={[
              styles.tab,
              { borderColor: selected ? c.primary : c.cardBorder },
              selected && { backgroundColor: hexToRgba(c.primary, 0.1) },
            ]}
            accessibilityRole="tab"
            accessibilityState={{ selected }}
          >
            <Text
              style={[
                styles.label,
                { color: selected ? c.primaryDark : c.textSecondary },
              ]}
              numberOfLines={1}
            >
              {t.label}
            </Text>
          </Pressable>
        );
      })}
    </View>
  );
}

function buildStyles(_c: AppColors) {
  return {
    row: {
      flexDirection: 'row' as const,
      gap: spacing[2],
      marginBottom: spacing[2],
    },
    tab: {
      flex: 1,
      paddingVertical: spacing[2.5],
      paddingHorizontal: spacing[2],
      borderRadius: radius.lg,
      borderWidth: StyleSheet.hairlineWidth,
      alignItems: 'center' as const,
    },
    label: {
      fontFamily: fontFamily.semiBold,
      fontSize: fontSize.sm,
      textAlign: 'center' as const,
    },
  };
}
