// apps/mobile/src/features/tournee-nurse/components/TourStopRouteChip.tsx
import { layoutRowCenter } from '@/theme/layout-styles';
import { useAppColors } from '@/theme/use-app-colors';
import { StyleSheet, View } from 'react-native';
import { Car, Route } from 'lucide-react-native';
import { Row } from '@/components/layout/primitives';
import { radius, spacing, iconSize, AppText, useStyles, font, type Theme } from '@/theme';
import { hexToRgba } from '@/theme/color-utils';
import { resolveTourStopRouteMetrics } from '@oneandlab/shared-utils';

type RouteStopLike = {
  distance_km_from_prev?: number | null;
  drive_min_from_prev?: number | null;
};

type Props = {
  stop: RouteStopLike;
};

export function TourStopRouteChip({ stop }: Props) {
  const c = useAppColors();
  const styles = useStyles(buildStyles);
  const metrics = resolveTourStopRouteMetrics(stop);
  if (!metrics) return null;

  const kmLabel = `${metrics.km.toFixed(1)} km`;
  const minLabel = metrics.min > 0 ? `~${metrics.min} min` : '—';

  return (
    <View
      style={[styles.chip, { backgroundColor: c.surfaceAlt, borderColor: c.borderLight }]}
      accessibilityLabel={`Trajet depuis le passage précédent : ${kmLabel}, environ ${metrics.min} minutes`}
    >
      <Row gap={spacing[1]} align="center" style={styles.segment}>
        <Route size={iconSize['2xs']} color={c.textSecondary} strokeWidth={2.4} />
        <AppText style={[styles.value, { color: c.textSecondary }]}>{kmLabel}</AppText>
      </Row>
      <View style={[styles.divider, { backgroundColor: hexToRgba(c.textTertiary, 0.28) }]} />
      <Row gap={spacing[1]} align="center" style={styles.segment}>
        <Car size={iconSize['2xs']} color={c.textSecondary} strokeWidth={2.4} />
        <AppText style={[styles.value, { color: c.textSecondary }]}>{minLabel}</AppText>
      </Row>
    </View>
  );
}

function buildStyles({ fontSize }: Theme) {
  return {
    chip: {
      ...layoutRowCenter(),
      alignSelf: 'flex-end' as const,
      borderRadius: radius.full,
      borderWidth: StyleSheet.hairlineWidth,
      paddingHorizontal: spacing[2],
      paddingVertical: spacing[1],
      gap: spacing[1.5],
    },
    segment: { flexShrink: 0 },
    divider: {
      width: StyleSheet.hairlineWidth,
      alignSelf: 'stretch' as const,
      marginVertical: 1,
    },
    value: {
      ...font.semiBold,
      fontSize: fontSize.xs,
      letterSpacing: -0.1,
    },
  };
}

// frontend/components/nurse/TourStopRouteChip.vue
<template>
  <div
    v-if="metrics"
    class="inline-flex items-center gap-1.5 self-end rounded-full border border-gray-200 bg-gray-50 px-2 py-1 dark:border-gray-700 dark:bg-gray-800/80"
    :aria-label="`Trajet depuis le passage précédent : ${kmLabel}, environ ${metrics.min} minutes`"
  >
    <span class="inline-flex shrink-0 items-center gap-1">
      <UIcon name="i-lucide-route" class="h-2.5 w-2.5 text-gray-500 dark:text-gray-400" />
      <span class="text-xs font-semibold text-gray-600 dark:text-gray-300">{{ kmLabel }}</span>
    </span>
    <span class="h-3 w-px shrink-0 bg-gray-300 dark:bg-gray-600" aria-hidden="true" />
    <span class="inline-flex shrink-0 items-center gap-1">
      <UIcon name="i-lucide-car" class="h-2.5 w-2.5 text-gray-500 dark:text-gray-400" />
      <span class="text-xs font-semibold text-gray-600 dark:text-gray-300">{{ minLabel }}</span>
    </span>
  </div>
</template>

<script setup lang="ts">
import { resolveTourStopRouteMetrics } from '@oneandlab/shared-utils';

const props = defineProps<{
  stop: Parameters<typeof resolveTourStopRouteMetrics>[0];
}>();

const metrics = computed(() => resolveTourStopRouteMetrics(props.stop));

const kmLabel = computed(() => `${metrics.value?.km.toFixed(1) ?? '0'} km`);

const minLabel = computed(() => {
  const min = metrics.value?.min ?? 0;
  return min > 0 ? `~${min} min` : '—';
});
</script>
